//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

final class ___VARIABLE_productName:identifier___Presenter: ___VARIABLE_productName:identifier___PresenterProtocol {

    // MARK: Properties

    private weak var view: ___VARIABLE_productName:identifier___ViewProtocol?
    private let router: ___VARIABLE_productName:identifier___WireframeProtocol

    // MARK: - Life cycle

    init(interface: ___VARIABLE_productName:identifier___ViewProtocol, router: ___VARIABLE_productName:identifier___WireframeProtocol) {
        self.view = interface
        self.router = router
    }

    deinit {
    }

    // MARK: - PresenterProtocol

    // MARK: ViewController -> Presenter

    func viewDidLoad() {
    }

    func viewWillAppear(_ animated: Bool) {
    }

    func viewDidAppear(_ animated: Bool) {
    }

    func viewWillDisappear(_ animated: Bool) {
    }

    func viewDidDisappear(_ animated: Bool) {
    }

    // MARK: Presenter -> ViewController
}
