//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

// MARK: - Wireframe

/// Routerが公開するメソッドを定義する.
///
/// Routerに適用する.
/// Presenter -> Wireframe
public protocol ___VARIABLE_productName:identifier___WireframeProtocol: class {
}

// MARK: - Presenter

/// PresenterがViewに対して公開するメソッド・通知オブジェクトを定義する.
///
/// Presenterに適用する.
public protocol ___VARIABLE_productName:identifier___PresenterProtocol: class {

    // MARK: ViewController -> Presenter

    func viewDidLoad()
    func viewWillAppear(_ animated: Bool)
    func viewDidAppear(_ animated: Bool)
    func viewWillDisappear(_ animated: Bool)
    func viewDidDisappear(_ animated: Bool)

    // MARK: Presenter -> ViewController
}

// MARK: - View

/// ViewがPresenterに対して公開するメソッドを定義する.
///
/// ViewControllerに適用する.
/// Presenter -> ViewController
public protocol ___VARIABLE_productName:identifier___ViewProtocol: class {
    var presenter: ___VARIABLE_productName:identifier___PresenterProtocol? { get set }
}
