//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

public final class ___VARIABLE_productName:identifier___Interactor: ___VARIABLE_productName:identifier___InteractorInputProtocol {

    // MARK: Properties

    public weak var presenter: ___VARIABLE_productName:identifier___InteractorOutputProtocol?

    // MARK: - Life cycle

    public init() {
    }

    // MARK: - InteractorInputProtocol
}
